version: '3.8'
services:
  postgres:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

volumes:
  pgdata:
